# Generated by Django 2.0.1 on 2018-07-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carNuber', models.CharField(max_length=20)),
                ('carLength', models.CharField(max_length=20)),
                ('carWidth', models.CharField(max_length=20)),
                ('persenal', models.CharField(max_length=20)),
                ('carModel', models.CharField(max_length=20)),
                ('endTime', models.DateTimeField()),
                ('x1', models.CharField(max_length=20)),
                ('x2', models.CharField(max_length=20)),
                ('x3', models.CharField(max_length=20)),
                ('y1', models.CharField(max_length=20)),
                ('y2', models.CharField(max_length=20)),
                ('y3', models.CharField(max_length=20)),
                ('machine', models.CharField(max_length=20)),
                ('supplier', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=20)),
            ],
        ),
    ]
